spring:
  datasource:
    url: jdbc:h2:file:./data/test
    driverClassName: org.h2.Driver
    username: test
    password: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

project:
  pool-cron: "*/5 * * * * *"
  cities:
    - "England, London"
    - "France, Parish"
    - "Turkey, Stambul"
#    - Error

